### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by mehranexpert** [RaulButuc/KeyLoggerPro#6]
Which file I should compile to exe ?

**Comment by RaulButuc** [comment]
Hi there @mehranexpert. At the moment being the keylogger is in the development state. Not all functionality has been implemented, thus even if you build the .exe right now, it won't really log the key strokes. However, if you still wish to compile it and produce the executable file you can follow these steps:

0) As a prerequisite I suggest you use Visual Studio (can be the free version).
1) Fork the GitHub repository.
2) Clone your forked repository locally.
3) Open the .sln file with Visual Studio.
4) Build and run the project.

If you have any further questions, don't hesitate to ask.
